name: Build Projects

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Android:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Android App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f net6.0-android

  iOS:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build iOS App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f:net6.0-ios
          
  MacCatalyst:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build macOS App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f net6.0-maccatalyst

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Windows App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory

  API:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build API App
      run: |
        APIProject=`find . -name GitStatus.API.csproj`
        echo $APIProject

        APIProjectDirectory=`dirname $APIProject`
        echo $APIProjectDirectory
        
        dotnet build -c Release $APIProjectDirectory

  Console:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Console App
      run: |        
        ConsoleProject=`find . -name GitStatus.ConsoleApp.csproj`
        echo $ConsoleProject

        ConsoleProjectDirectory=`dirname $ConsoleProject`
        echo $ConsoleProjectDirectory

        dotnet build -c Release $ConsoleProjectDirectory

  Web:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Web App
      run: |                   
        WebProject=`find . -name GitStatus.Web.csproj`
        echo $WebProject

        WebProjectDirectory=`dirname $WebProject`
        echo $WebProjectDirectory

        dotnet build -c Release $WebProjectDirectory

  GitHubApiStatus:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Web App
      run: |                  
        GitHubApiStatusExtensionsProject=`find . -name GitHubApiStatus.Extensions.csproj`
        echo $GitHubApiStatusExtensionsProject

        GitHubApiStatusExtensionsProjectDirectory=`dirname $GitHubApiStatusExtensionsProject`
        echo $GitHubApiStatusExtensionsProjectDirectory
  
        dotnet build -c Release $GitHubApiStatusExtensionsProjectDirectory
