name: Build Projects

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Inject_API_Key:
      runs-on: macos-latest
      
      env:
        GitHubPersonalAccessToken: ${{ secrets.GitHubPersonalAccessToken }}

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET Core v2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'   

      - name: Inject GitHub Personal Access Token
        run: |
          GitHubConstantsFile=`find . -name GitHubConstants.cs | head -1`

          echo GitHubConstantsFile = $GitHubConstantsFile

          sed -i '' "s/PersonalAccessToken = \"\"/PersonalAccessToken = \"$GitHubPersonalAccessToken\"/g" "$GitHubConstantsFile"

          echo "Finished Injecting GitHub Personal Access Token"
      
      - name: Restore NuGet 
        run: |
          nuget restore ./Src

    Android:
      runs-on: macos-latest
      
      needs: Inject_API_Key

      steps:
      - uses: actions/checkout@v1

      - name: Restore Android NuGet Packages
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll -t:restore ./Src/GitStatus.Android/GitStatus.Android.csproj
        
      - name: Build Android App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./Src/GitStatus.Android/GitStatus.Android.csproj /verbosity:normal /p:Configuration=Release     

    API:
      runs-on: macos-latest

      needs: Inject_API_Key

      steps:
      - uses: actions/checkout@v1

      - name: Build API App
        run: |                    
          dotnet build -c Release ./Src/GitStatus.API/GitStatus.API.csproj

    Console:
      runs-on: macos-latest

      needs: Inject_API_Key

      steps:
      - uses: actions/checkout@v1

      - name: Build Console App
        run: |                    
          dotnet build -c Release ./Src/GitStatus.ConsoleApp/GitStatus.ConsoleApp.csproj

    Web:
      runs-on: macos-latest

      needs: Inject_API_Key

      steps:
      - uses: actions/checkout@v1

      - name: Build Web App
        run: |                    
          dotnet build -c Release ./Src/GitStatus.Web/GitStatus.Web.csproj

    GitHubApiStatus:
      runs-on: macos-latest

      needs: Inject_API_Key

      steps:
      - uses: actions/checkout@v1

      - name: Build Web App
        run: |                    
          dotnet build -c Release ./Src/GitHubApiStatus.Extensions/GitHubApiStatus.Extensions.csproj