name: Build Projects

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Android App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f:net9.0-android -c Release

  iOS:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f:net9.0-ios -c Release
          
  MacCatalyst:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build macOS App
        run: |
          MobileProject=`find . -name GitStatus.Mobile.csproj`
          echo $MobileProject

          MobileProjectDirectory=`dirname $MobileProject`
          echo $MobileProjectDirectory

          dotnet build $MobileProjectDirectory -f:net9.0-maccatalyst -c Release

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Windows App
        run: |
          dotnet build ./samples/GitStatus.Mobile/ -c Release -f net9.0-windows10.0.19041.0

  API:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET v9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build API App
      run: |
        APIProject=`find . -name GitStatus.API.csproj`
        echo $APIProject

        APIProjectDirectory=`dirname $APIProject`
        echo $APIProjectDirectory
        
        dotnet build -c Release $APIProjectDirectory

  Console:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET v9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build Console App
      run: |        
        ConsoleProject=`find . -name GitStatus.ConsoleApp.csproj`
        echo $ConsoleProject

        ConsoleProjectDirectory=`dirname $ConsoleProject`
        echo $ConsoleProjectDirectory

        dotnet build -c Release $ConsoleProjectDirectory

  Web:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET v9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build Web App
      run: |                   
        WebProject=`find . -name GitStatus.Web.csproj`
        echo $WebProject

        WebProjectDirectory=`dirname $WebProject`
        echo $WebProjectDirectory

        dotnet build -c Release $WebProjectDirectory

  GitHubApiStatus:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET v9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        

    - name: Build Web App
      run: |                  
        GitHubApiStatusExtensionsProject=`find . -name GitHubApiStatus.Extensions.csproj`
        echo $GitHubApiStatusExtensionsProject

        GitHubApiStatusExtensionsProjectDirectory=`dirname $GitHubApiStatusExtensionsProject`
        echo $GitHubApiStatusExtensionsProjectDirectory
  
        dotnet build -c Release $GitHubApiStatusExtensionsProjectDirectory
