name: Run Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    UnitTests:
      runs-on: macos-15
      
      env:
        GitHubPersonalAccessToken: ${{ secrets.GitHubPersonalAccessToken }}

      steps:
      - uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
            7.0.x
            6.0.x
            3.1.x
            2.1.x

      - name: Inject GitHub Personal Access Token
        run: |
          GitHubConstantsFile=`find . -name GitHubConstants.cs | head -1`

          echo GitHubConstantsFile = $GitHubConstantsFile

          sed -i '' "s/PersonalAccessToken = \"\"/PersonalAccessToken = \"$GitHubPersonalAccessToken\"/g" "$GitHubConstantsFile"

          echo "Finished Injecting GitHub Personal Access Token"

      - name: Run GitHubApiStatus.UnitTests
        run: |
          GitHubApiStatusUnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $GitHubApiStatusUnitTestProject

          GitHubApiStatusUnitTestDirectory=`dirname $GitHubApiStatusUnitTestProject`
          echo $GitHubApiStatusUnitTestDirectory
          
          dotnet test $GitHubApiStatusUnitTestDirectory -c 'Release'

      - name: Run GitHubApiStatus.Extensions.UnitTests
        run: |
          GitHubApiStatusExtensionsUnitTestProject=`find . -name GitHubApiStatus.Extensions.UnitTests.csproj`
          echo $GitHubApiStatusExtensionsUnitTestProject

          GitHubApiStatusExtensionsUnitTestDirectory=`dirname $GitHubApiStatusExtensionsUnitTestProject`
          echo $GitHubApiStatusExtensionsUnitTestDirectory

          dotnet test $GitHubApiStatusExtensionsUnitTestDirectory -c 'Release'
