name: Run Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    UnitTests:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.*' # SDK Version to use.
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $UnitTestProject

          UnitTestDirectory=`dirname $UnitTestProject`
          echo $UnitTestDirectory
          
          dotnet test $UnitTestDirectory -c 'Release'
