name: Run Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    UnitTests:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET Core v2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'      

      - name: Run Unit Tests
        run: |
          GitHubApiStatusUnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $GitHubApiStatusUnitTestProject

          GitHubApiStatusUnitTestDirectory=`dirname $GitHubApiStatusUnitTestProject`
          echo $GitHubApiStatusUnitTestDirectory

          GitHubApiStatusExtensionsUnitTestProject=`find . -name GitHubApiStatus.Extensions.UnitTests.csproj`
          echo $GitHubApiStatusExtensionsUnitTestProject

          GitHubApiStatusExtensionsUnitTestDirectory=`dirname $GitHubApiStatusExtensionsUnitTestProject`
          echo $GitHubApiStatusExtensionsUnitTestDirectory
          
          dotnet test $GitHubApiStatusUnitTestDirectory -c 'Release'
          dotnet test $GitHubApiStatusExtensionsUnitTestDirectory -c 'Release'
