name: Run Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    UnitTests:
      runs-on: macos-latest
      
      env:
        GitHubPersonalAccessToken: ${{ secrets.GitHubPersonalAccessToken }}

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET Core v2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'   

      - name: Inject GitHub Personal Access Token
        run: |
          GitHubConstantsFile=`find . -name GitHubConstants.cs | head -1`

          echo GitHubConstantsFile = $GitHubConstantsFile

          sed -i '' "s/PersonalAccessToken = \"\"/PersonalAccessToken = \"$GitHubPersonalAccessToken\"/g" "$GitHubConstantsFile"

          echo "Finished Injecting GitHub Personal Access Token"

      - name: Run GitHubApiStatus.UnitTests
        run: |
          GitHubApiStatusUnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $GitHubApiStatusUnitTestProject

          GitHubApiStatusUnitTestDirectory=`dirname $GitHubApiStatusUnitTestProject`
          echo $GitHubApiStatusUnitTestDirectory
          
          dotnet test $GitHubApiStatusUnitTestDirectory -c 'Release' -v d

      - name: Run GitHubApiStatus.Extensions.UnitTests
        run: |
          GitHubApiStatusExtensionsUnitTestProject=`find . -name GitHubApiStatus.Extensions.UnitTests.csproj`
          echo $GitHubApiStatusExtensionsUnitTestProject

          GitHubApiStatusExtensionsUnitTestDirectory=`dirname $GitHubApiStatusExtensionsUnitTestProject`
          echo $GitHubApiStatusExtensionsUnitTestDirectory

          dotnet test $GitHubApiStatusExtensionsUnitTestDirectory -c 'Release'
