name: Run Unit Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  
    UnitTests
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Restore NuGet 
        run: |
          cd Src
          nuget restore         
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $UnitTestProject

          UnitTestDirectory=`dirname $UnitTestProject`
          echo $UnitTestDirectory
          
          dotnet test  -c "Release" $UnitTestDirectory
