name: Run Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    UnitTests:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Run Unit Tests
        run: |   
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh ./dotnet-install.sh --version SDK 5.0.100-rc.2

          UnitTestProject=`find . -name GitHubApiStatus.UnitTests.csproj`
          echo $UnitTestProject

          UnitTestDirectory=`dirname $UnitTestProject`
          echo $UnitTestDirectory
          
          dotnet test $UnitTestDirectory -c 'Release'
